### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by Calinou** [lennart-g/blender-md2-importer#1]
The repository currently doesn't seem to contain any license. Could you add one, please? Since Blender itself is licensed under GPLv2 or later, this add-on should also be licensed under the same licenes for compliance. See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

**Comment by lennart-g** [comment]
I chose GPLv3, please let me know if I did anything wrong with the license as I have zero experience with those. Also, thanks for addressing this :)

**Comment by Calinou** [comment]
Thanks :slightly_smiling_face: 

It would likely be better to go with "GPLv2 or later" since it's the same license as Blender. As the [license page](https://www.blender.org/about/license/) says:

> ### Sharing or selling Blender add-ons (Python scripts)
>
> Blender’s Python API is an integral part of the software, used to define the user interface or develop tools for example. The GNU GPL license therefore requires that such scripts (if published) are being shared under a GPL compatible license. You are free to sell such scripts, but the sales then is restricted to the download service itself. Your customers will receive the script under the same license (GPL), with the same free conditions as everyone has for Blender.

The issue is that the GPLv3 isn't compatible with GPLv2, since it adds more restrictions on top. However, "GPLv2 or later" is compatible with both the GPLv2 and GPLv3.
