### ISSUE TITLE
Plugin installation problem.

### ISSUE THREAD

**Issue by Mulligan81** [lennart-g/blender-md2-importer#5]
Hello
To install the plugin I've followed the instructions [here ](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-and-Uninstallation) as advised but after selecting and installing the _.zip_ file there is NO _WIP Quake 2 Model Import_ in the plugin list nor in the _file->import_. I've tried it with blender 2.8x and 2.9x - the same effect still not able so find and use the plugin...
Please help!

**Comment by lennart-g** [comment]
Hi @Mulligan81 ,

sadly, the installation process is still overly complex. I just checked on Windows 10 with blender 2.83 LTS if it still works.
When you check the activate plugin checkbox and an error pops up, just keep going with the next step mentioned in the readme, the `pillow` installation.

I updated the README for more clarity. If your installation still fails, please state precisely what you did, on what OS, what blender version, what sort of error was shown / in what step the installation failed.
